name: Docker Build
on:
  push:
    branches:
      - add-search-bar-ui

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker_hub_name/image_name:latest
          secrets: |
            "DB_CONFIG=${{ secrets.DB_CONFIG }}"