name: Docker Build
on:
  push:
    branches:
      - add-search-bar-ui

id: docker_build
uses: docker/build-push-action@v2
with:
  push: true
  tags: g2idocker/auth:latest
  secrets: |
      "DB_CONFIG=${{ secrets.DB_CONFIG }}"